### ISSUE TITLE
Actual travel time

### ISSUE THREAD

**Issue by Haroenv** [Haroenv/maps-checker#3]
3/ Toon het aanbevolen traject samen met de verkeersdruktekleuren op een
kaart (gebruik Google Maps vs. 3). Vermeld tevens groot en duidelijk de door
Google Maps op dat moment geschatte reistijd (2p)

- [x] link google maps
- [x] embed map
- [x] travel time 
- [x] traffic (is this even possible?)

**Comment by dervondenbergen** [comment]
:+1:
